WebApplication/newTRM/newTRM/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using newTRM.Classes;
using newTRM.NewModels;
using newTRM.NewModels.ApiModels;

namespace newTRM.Controllers
{
    [Authorize(Roles = "Employee,Admin")]
    public class ReportController : Controller
    {
        [HttpPost]
        public IActionResult NoteReport(Note n)
        {
            var m = new NoteReportModel();
            m.note = n;
            return View(m);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<IActionResult> CreateNoteReport(CompleteModel model, int noteId)
        public async Task<IActionResult> CreateNoteReport(NoteReportModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //make the proper model-->pictures to Byte[]
                    CompleteApiReport r = new CompleteApiReport(model.completeModel);
                    //send POST to API
                    ApiHelper.NewCompleteReport(r);
                    //delete note
                    await ApiHelper.MakeRequest(ApiTypes.DELETE, new Note(), model.note.Id);
                    //return to index
                    return RedirectToAction("Index", "TRM");
                }
                catch (Exception e)
                {
                    //var m = new NoteReportModel();
                    //m.completeModel = model;
                    //m.note = new Note { Id = noteId };
                    return View("NoteReport", model);
                }
            }
            //var nrm = new NoteReportModel();
            //nrm.completeModel = model;
            //nrm.note = new Note { Id = noteId };
            return View(model);
        }


        public IActionResult Create()
        {
            return View(new CompleteModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CompleteModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    //make the proper model-->pictures to Byte[]
                    CompleteApiReport r = new CompleteApiReport(model);
                    //send POST to API
                    ApiHelper.NewCompleteReport(r);
                    //return to index
                    return RedirectToAction("Index", "TRM");
                }
                catch (Exception e)
                {
                    return View(model);
                }
            }
            return View(model);
        }

        public async Task<JsonResult> AutocompleteCustomers()
        {
            List<Customer> customers = await ApiHelper.MakeRequest(ApiTypes.GET, new Customer());
            var c = customers.Select(x => new { id = x.Id, name = x.Name, branch = x.Branch })
                .GroupBy(x => new { x.name, x.branch })
                .Distinct()
                .Select(y => new
                {
                    id = y.FirstOrDefault().id,
                    name = y.First().name,
                    branch = y.First().branch
                })
                .ToList();
            return Json(c);
        }
        public async Task<JsonResult> AutocompleteEngines()
        {
            List<ApiEngine> engines = await ApiHelper.MakeRequest(ApiTypes.GET, new ApiEngine());
            var e = engines.Select(x => new
            {
                id = x.Id,
                manufacturer = x.Manufacturer,
                type = x.Type,
                spindle = x.Spindle,
                coolantoutside = x.Coolantoutside,
                coolantinside = x.Coolantinside,
                power = x.Power,
                rotationalspeed = x.Rotationalspeed,
                feed = x.Feed,
                activationyear = x.Activationyear,
                programming = x.Programming,
                controlling = x.Controlling,
                hourlyrate = x.Hourlyrate
            })
                .GroupBy(x => new
                {
                    x.manufacturer,
                    x.type,
                    x.spindle,
                    x.coolantoutside,
                    x.coolantinside,
                    x.power,
                    x.rotationalspeed,
                    x.feed,
                    x.activationyear,
                    x.programming,
                    x.controlling,
                    x.hourlyrate
                })
                .Distinct()
                .Select(y => new
                {
                    id = y.FirstOrDefault().id,
                    manufacturer = y.First().manufacturer,
                    type = y.First().type,
                    spindle = y.First().spindle,
                    coolantoutside = y.First().coolantoutside,
                    coolantinside = y.First().coolantinside,
                    power = y.First().power,
                    rotationalspeed = y.First().rotationalspeed,
                    feed = y.First().feed,
                    activationyear = y.First().activationyear,
                    programming = y.First().programming,
                    controlling = y.First().controlling,
                    hourlyrate = y.First().hourlyrate
                })
                .ToList();
            return Json(e);
        }
        public async Task<JsonResult> AutocompleteMaterials()
        {
            List<Material> materials = await ApiHelper.MakeRequest(ApiTypes.GET, new Material());
            var m = materials.Select(x => new
            {
                id = x.Id,
                designation = x.Designation,
                dincode = x.Dincode,
                encode = x.Encode,
                hardnesshb = x.HardnessHB,
                hardnesshrc = x.HardnessHRC,
                materialgroup = x.Materialgroup,
                crprc = x.CRpercent,
                wprc = x.Wpercent,
                sprc = x.Spercent,
                siprc = x.SIpercent,
                mnprc = x.MNpercent,
                nprc = x.NBpercent,
                niprc = x.NIpercent,
                vprc = x.Vpercent,
                moprc = x.MOpercent,
                cuprc = x.CUpercent,
                tiprc = x.TIpercent,
                pbprc = x.PBpercent,
                nbprc = x.NBpercent,
                coprc = x.COpercent,
                feprc = x.FEpercent,
                ceprc = x.CEpercent,
                alprc = x.ALpercent,
                cprc = x.Cpercent,
                znprc = x.ZNpercent,
                bprc = x.Bpercent,
                mgprc = x.MGpercent
            })
                .GroupBy(x => new
                {
                    x.designation,
                    x.dincode,
                    x.encode,
                    x.hardnesshb,
                    x.hardnesshrc,
                    x.materialgroup,
                    x.crprc,
                    x.wprc,
                    x.sprc,
                    x.siprc,
                    x.mnprc,
                    x.nprc,
                    x.niprc,
                    x.vprc,
                    x.moprc,
                    x.cuprc,
                    x.tiprc,
                    x.pbprc,
                    x.nbprc,
                    x.coprc,
                    x.feprc,
                    x.ceprc,
                    x.alprc,
                    x.cprc,
                    x.znprc,
                    x.bprc,
                    x.mgprc
                })
                .Distinct()
                .Select(y => new
                {
                    id = y.FirstOrDefault().id,
                    designation = y.First().designation,
                    dincode = y.First().dincode,
                    encode = y.First().encode,
                    hardnesshb = y.First().hardnesshb,
                    hardnesshrc = y.First().hardnesshrc,
                    materialgroup = y.First().materialgroup,
                    crprc = y.First().crprc,
                    wprc = y.First().wprc,
                    sprc = y.First().sprc,
                    siprc = y.First().siprc,
                    mnprc = y.First().mnprc,
                    nprc = y.First().nprc,
                    niprc = y.First().niprc,
                    vprc = y.First().vprc,
                    moprc = y.First().moprc,
                    cuprc = y.First().cuprc,
                    tiprc = y.First().tiprc,
                    pbprc = y.First().pbprc,
                    nbprc = y.First().nbprc,
                    coprc = y.First().coprc,
                    feprc = y.First().feprc,
                    ceprc = y.First().ceprc,
                    alprc = y.First().alprc,
                    cprc = y.First().cprc,
                    znprc = y.First().znprc,
                    bprc = y.First().bprc,
                    mgprc = y.First().mgprc
                })
                .ToList();
            return Json(m);
        }
    }
}

WebApplication/newTRM/newTRM/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using newTRM.Data;
using Microsoft.AspNetCore.Identity;
using newTRM.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Configuration;

namespace newTRM.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        UserManager<ApplicationUser> userManager;
        IConfiguration config;
        //in html-->IsInRole() to check if user is allowed to see

        public RoleController(UserManager<ApplicationUser> _userManager, IConfiguration _config)
        {

            userManager = _userManager;
            config = _config;
        }

        public IActionResult RoleManagement()
        {
            return View(GetUsers());
        }
        [HttpPost]
        public async Task<IActionResult> AddUser(string Email, string Password)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = Email, Email = Email };
                var result = await userManager.CreateAsync(user, Password);
                if (result.Succeeded)
                {
                    return View("RoleManagement", GetUsers());
                }
            }
            return View("RoleManagement", GetUsers());
        }

        private List<UsersModel> GetUsers()
        {
            var users = userManager.Users.Select(x => new UsersModel
            {
                UserId = x.Id,
                Username = x.UserName,
                Email = x.Email
            }).ToList();
            users.ForEach(x =>
            {
                x.IsAdmin = userManager.IsInRoleAsync(userManager.FindByNameAsync(x.Username).Result, "Admin").Result;
            });
            users.ForEach(x =>
            {
                x.IsEmployee = userManager.IsInRoleAsync(userManager.FindByNameAsync(x.Username).Result, "Employee").Result;
            });
            return users;
        }

        public async Task<IActionResult> RevokeRole(string id, string role)
        {
            var superadminId = config.GetSection("UserSettings")["UserId"];
            var user = userManager.FindByIdAsync(id).Result;
            if (!(user.Id.Equals(superadminId) && role.Equals("Admin")))
            {
                await userManager.RemoveFromRoleAsync(user, role);
            }
            return View("RoleManagement", GetUsers());
        }
        public async Task<IActionResult> GiveRole(string id, string role)
        {
            await userManager.AddToRoleAsync(userManager.FindByIdAsync(id).Result, role);
            return View("RoleManagement", GetUsers());
        }
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = userManager.FindByIdAsync(id).Result;
            var superadminId = config.GetSection("UserSettings")["UserId"];
            if (!user.Id.Equals(superadminId))
            {
                await userManager.DeleteAsync(user);
            }
            return View("RoleManagement", GetUsers());
        }
    }
}

WebApplication/newTRM/newTRM/Controllers/TRMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using System.Data;
using Npgsql;
using newTRM.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using newTRM.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using newTRM.Classes;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Text;
using Newtonsoft.Json;
using newTRM.NewModels.ApiModels;
using newTRM.NewModels;

namespace newTRM.Controllers
{
    public class TRMController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        public TRMController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;

        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> NotePartial()
        {
            List<Note> notes = await ApiHelper.MakeRequest(ApiTypes.GET, new Note());
            return PartialView("NotePartial", notes);
        }
        public async Task<int> DeleteNote(int noteId)
        {
            ApiHelper.MakeRequest(ApiTypes.DELETE, new Note(), noteId);
            return 1;
        }

        [Authorize]
        public IActionResult NewProjectFolder()
        {
            return View();
        }


        [Authorize(Roles = "Employee,Admin")]
        public IActionResult Search()
        {
            return View(new Search());
        }
        [HttpPost]
        [Authorize(Roles = "Employee,Admin")]
        public IActionResult Search(Search s)
        {
            try
            {
                List<ApiReport> reports = ApiHelper.DoSearch(s).Result;
                return View("SearchResults", reports);
            }
            catch (Exception e)
            {
                return View(s);
            }

        }
        [Authorize(Roles = "Employee,Admin")]
        public IActionResult ShowReport(int id)
        {
            try
            {
                var fileStream = new FileStream(ApiHelper.GetPdf(id).Result, FileMode.Open, FileAccess.Read);
                var fsResult = new FileStreamResult(fileStream, "application/pdf");

                return fsResult;
            }
            catch (Exception e)
            {
                return null;
            }
        }
        [Authorize(Roles = "Employee,Admin")]
        public IActionResult EditReport(int id)
        {
            //not implemented

            return View("Index");
        }
        [Authorize(Roles = "Employee,Admin")]
        public async Task<IActionResult> DeleteReport(int id)
        {
            //even tho it uses the old Report-Model it actually should still work
            await ApiHelper.MakeRequest(ApiTypes.DELETE, new Report(), id);
            return View("Search", new Search());
        }
    }

}

WebApplication/newTRM/newTRM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - newTRM</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="TRM" asp-action="Index" class="navbar-brand">TRM</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("Employee") || User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Report" asp-action="Create">Make new Report</a></li>
                    }
                    @if (User.IsInRole("Employee") || User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="TRM" asp-action="Search">Search</a></li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Role" asp-action="RoleManagement">User-Management</a></li>
                    }

                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - newTRM</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
        <link href="~/lib/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
        <link href="~/lib/jquery-ui-1.12.1.custom/jquery-ui.theme.css" rel="stylesheet" />
        <link href="~/lib/jquery-ui-1.12.1.custom/jquery-ui.structure.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>


    @RenderSection("Scripts", required: false)
</body>
</html>